# Generated by Django 3.0 on 2020-01-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200111_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='real_type',
        ),
        migrations.RemoveField(
            model_name='specialentry',
            name='real_type',
        ),
    ]
