# Generated by Django 3.0 on 2020-01-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200111_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alias',
            field=models.CharField(max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AddField(
            model_name='tag',
            name='alias',
            field=models.CharField(max_length=100, null=True, verbose_name='alias'),
        ),
    ]
