# Generated by Django 3.0 on 2020-01-23 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200117_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='a_email',
            field=models.CharField(blank=True, max_length=100, verbose_name='author email'),
        ),
        migrations.AddField(
            model_name='comment',
            name='a_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='author name'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Author'),
        ),
    ]
