ENTRIES_PER_PAGE = 6

ENTRIES_SORT_TYPE_PUBDATE_DESC = 'pub_date_desc'
ENTRIES_SORT_TYPE_PUBDATE_ASC = 'pub_date_asc'

ENTRIES_SORT_TYPE = ENTRIES_SORT_TYPE_PUBDATE_DESC

RESP_STATUS_SUCCESS = 'success'
RESP_STATUS_ERROR = 'error'
RESP_STATUS_SERVER_ERROR = 'server_error'
RESP_ALIAS_REDIRECT = 'redirect'
